Handle errors and done signals from consumers
goat-project/goat pull request #8
Opened 2018-10-30 13:25 UTC by tomsik68

This PR adds:
1. Handling of consumer startup errors. 
2. Waiting until consumers are finished before exiting the method (this prevents goroutine leaks). This is achieved by joining the `DoneChannel`s using `AndDone`. When EOF is encountered, the record channels are closed and then `Process` waits until all consumers are done. If an error occurs, all consumers are cancelled using `cancelConsumers` which uses `context`.

2018-10-31 08:27 UTC, amarthadan requested changes

2018-10-31 08:27 UTC, amarthadan commented on common/channels.go
> +package common
According to Go best practices, package names shouldn't be meaningless:
> Packages named util, common, or misc provide clients with no sense of what the package contains. This makes it harder for clients to use the package and makes it harder for maintainers to keep the package focused. Over time, they accumulate dependencies that can make compilation significantly and unnecessarily slower, especially in large programs. And since such package names are generic, they are more likely to collide with other packages imported by client code, forcing clients to invent names to distinguish them.

Source: [https://blog.golang.org/package-names](https://blog.golang.org/package-names)

2018-10-31 08:27 UTC, amarthadan commented on importer/importer.go
> +	defer cancelConsumers()
If I understand it correctly, for now, this does nothing. Am I right? Because you're not using anything from the context in the `Consume*` methods. I would expect pulling out the done channel from the context and not creating a custom one. Or did I totally misunderstand it?

2018-10-31 09:06 UTC, tomsik68 commented on importer/importer.go
> +	defer cancelConsumers()
> for now, this does nothing. Am I right?

That's right. This PR just adds handling of whatever consumers do and changes consumer interface. Consumer implementation will be added in another PR, but I can add it to this one if you think it's better.

> I would expect pulling out the done channel from the context and not creating a custom one. Or did I totally misunderstand it?

Actually, we need a done channel in both directions. `context` provides a done channel which is supposed to be checked by consumers. This done channel is closed when parent cancels goroutine - `cancelConsumers` is called, timeout expired, etc.

Other direction of the done channel is used by a consumer to signal that it is done consuming. If this channel wasn't there, there would be a goroutine leak.

2018-10-31 09:10 UTC, Misenko commented on importer/importer.go
> +	defer cancelConsumers()
> That's right. This PR just adds handling of whatever consumers do and changes consumer interface. Consumer implementation will be added in another PR, but I can add it to this one if you think it's better.

That's ok, feel free to put it in a separate PR, I just wanted to be sure.

> Actually, we need a done channel in both directions. context provides a done channel which is supposed to be checked by consumers. This done channel is closed when parent cancels goroutine - cancelConsumers is called, timeout expired, etc.

> Other direction of the done channel is used by a consumer to signal that it is done consuming. If this channel wasn't there, there would be a goroutine leak.

Did not know that. Alright then, seems legit :+1:

2018-11-05 07:22 UTC, tomsik68 commented on common/channels.go
> +package common
Agreed. I think creating a package for a type alias and single function might be overkill, so I've moved it to the consumer package.

2018-11-05 07:25 UTC, amarthadan approved these changes

2018-11-05 07:32 UTC, merged